### ISSUE TITLE
BUG on Receptor configuration - No verifysignature param

### ISSUE THREAD

**Issue by tanganellilore** [ansible/tower-operator#1132]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Good Morning Team,

I dicover a bug on Receptor configuration ConfigMap during the deployment of AWX. 
This bug can be refferred to AWX commit: [84f2b91105c959c4d89a63063cca441f3d67fc0f](https://github.com/ansible/awx/commit/84f2b91105c959c4d89a63063cca441f3d67fc0f) this [PR](https://github.com/ansible/awx/pull/13200) where introduced the  `sign_work` variable and `work_signing_enabled(config_data)` fuction that check if `work-verification` section is preset in the `/etc/receptor/receptor.conf` .

To align `awx-operator` to this commint we need to add [awx-operator/roles/installer/templates/configmaps/config.yaml.j2](https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/configmaps/config.yaml.j2), in `receptor_conf ` section the following part:
Adding  on key `work-command`, `work-kubernetes`, `work-kubernetes`
```yaml
verifysignature: true
```
Adding this section
```yaml
- work-verification:
    publickey: /etc/receptor/work_public_key.pem
```

Moreover, another issue is realted the installation bundle of execution_node. Due to the fact that `sign_work` is not poulated, the respective `verifysignature` key in the bundle is empty, and this create issue on the receptor configuration.

I will try to propose you a PR to fix this issue in a short time and I will try tro introduce a variable to enable/disable the `sign_work`.

### AWX Operator version

1.1.0

### AWX version

21.9.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.23.2

### Modifications

no

### Steps to reproduce

Update or install 21.9.0 and add new execution node.

Download the instalaltion bundle and you will se that verifysignature is missing.
If you enable it, execution node not work, because controller node not have the same setting

### Expected results

verifysignature enabled and working

### Actual results

Remote error: ERROR: could not parse response: ERROR: could not verify signature: signature is empty

**Comment by AlanCoding** [comment]
There is a promising fix at https://github.com/ansible/awx/pull/13253, and that will likely make any operator changes a mute point.

The installer bundle for remote execution nodes were always intended to have verifywork set to True, and it appears that it was set to False simply as a recent regression.

**Comment by tanganellilore** [comment]
This will cover only bundle installation, but not the verification   key on awx side.

Due to this commit: https://github.com/ansible/awx/commit/84f2b91105c959c4d89a63063cca441f3d67fc0f
If we don't add `work-verification` on the receptor side in EE container (on k8s deployment) and we don't bind the sign key,  I think this will not resolve, because receptor on EE will not have a bind key to sign and backend will not run a job with sign key.
Tomorrow i will send you the error of 21.9.0 k8s deployment with verifysignature a true on external execution node.

**Comment by tanganellilore** [comment]
Below, the info promised:

AWX: 21.9.0
receptor.conf
```yaml
---
- node:
    id: XX.XX.XX.XX

- work-verification:
    publickey: /etc/receptor/work_public_key.pem

- log-level: info

- control-service:
    service: control
    filename: /var/run/receptor/receptor.sock
    permissions: 0660
    tls: tls_server
- tls-server:
    name: tls_server
    cert: /etc/receptor/tls/XX.XX.XX.XX.crt
    key: /etc/receptor/tls/XX.XX.XX.XX.key
    clientcas: /etc/receptor/tls/ca/mesh-CA.crt
    requireclientcert: true
    mintls13: False

- tls-client:
    name: tls_client
    cert: /etc/receptor/tls/XX.XX.XX.XX.crt
    key: /etc/receptor/tls/XX.XX.XX.XX.key
    rootcas: /etc/receptor/tls/ca/mesh-CA.crt
    insecureskipverify: false
    mintls13: False
- tcp-listener:
    port: 27199
    tls: tls_server

- work-command:
    worktype: ansible-runner
    command: ansible-runner
    params: worker
    allowruntimeparams: True
    verifysignature: True
```

If i run the healthcheck on awx side, If i run the healthcheck 
AWXside:
`Remote error: ERROR: could not parse response: ERROR: could not verify signature: signature is empty`

Receptor Side:
```
INFO 2022/12/02 13:26:57 Connection established with awx-54c6f6fbf5-6pmqf
INFO 2022/12/02 13:26:57 Known Connections:
INFO 2022/12/02 13:26:57    XX.XX.XX.XX: awx-54c6f6fbf5-6pmqf
INFO 2022/12/02 13:26:57    awx-54c6f6fbf5-6pmqf:  XX.XX.XX.XX
INFO 2022/12/02 13:26:57 Routing Table:
INFO 2022/12/02 13:26:57    awx-54c6f6fbf5-6pmqf via awx-54c6f6fbf5-6pmqf
ERROR 2022/12/02 13:27:19 could not verify signature: signature is empty
ERROR 2022/12/02 13:27:40 could not verify signature: signature is empty
```

You can see that with `verifysignature` we still have the issue, due to the fact that on AWX side we don't have the `work-verification` key on K8s Configmap.
Please see this line of code: https://github.com/ansible/awx/blob/devel/awx/main/tasks/receptor.py#L175
If `work-verification` in not present on awx side, everything will be runned without signkey from AWX side, but receptor expect to have signed command.

So we are in a loop also with the PR proposed.

**Comment by AlanCoding** [comment]
It does make sense to me that `- work-verification:` should be added to the K8s Configmap as you say.

For remote execution nodes, that needs to be set up, because that feature assumes that work will be signed. That might be administrative cleanup tasks, or running jobs in the remote execution node. Both should set signwork based on the presence of that entry in the receptor config... because you need that to be able to sign work.

Normal AWX installs without remote execution nodes run all jobs as container_group jobs. There are no administrative tasks ran for those, and jobs have signwork set to False as a special case for container_group jobs. I don't know how it was working before this, so I'll have to say I don't know right now.

**Comment by tanganellilore** [comment]
I assume that before works as you think.
By default all works are signed but with the last update of awx this was changed and are missing these few params.

I don't know if the correct way is to "force" signed work to be true on all cases, but in any case, we need to add `- work-verification:` on AWX side and also mount the public key to the container.

In my PR I "suppose" to maintain both options (sign yes or not) on K8s deployment (to allow people to choice it, instead force him), but I can create a pull request with only minimum requirements, without problem.

**Comment by fosterseth** [comment]
@tanganellilore thanks for digging into this.

We introduced a bug, which was fixed here https://github.com/ansible/awx/pull/13253

a couple of weeks ago we opened a PR to disable work signing, intended only for development purposes (docker-based app, not k8s), but we changed a line that affected k8s deployments, which was not intended.

For awx k8s deployments, work verification should always be enabled.

**Comment by tanganellilore** [comment]
@fosterseth , in that case `- work-verification:` still required for works in signed way, see https://github.com/ansible/awx/blob/devel/awx/main/tasks/receptor.py#L175

I will change my PR with requested modification

**Comment by tanganellilore** [comment]
fixed with last release of AWX and this PR: https://github.com/ansible/awx/pull/13296

**Comment by sakeebshaikh74** [comment]
I am still facing the issue with the 

apiVersion: v2
appVersion: 2.1.0
description: A Helm chart for the AWX Operator
name: awx-operator
type: application
version: 2.1.0


![image](https://github.com/ansible/awx-operator/assets/163878399/84c1094e-6628-49f6-b140-0d050c756e80)


error logs from receptor server

DEBUG 2024/03/19 10:37:16 Client connected to control service awx-task-f9bf5d469-qj5zd:jVs2UZdC
ERROR 2024/03/19 10:37:16 could not verify signature: token is expired by 58m56.745392614s
DEBUG 2024/03/19 10:37:16 Client disconnected from control service awx-task-f9bf5d469-qj5zd:jVs2UZdC
DEBUG 2024/03/19 10:37:22 Sending service advertisement: &{ilgss1358 control 2024-03-19 10:37:22.829743097 +0200 IST m=+125.016580937 2 map[type:Control Service] [{ansible-runner true}]}
DEBUG 2024/03/19 10:37:22 Received routing update Vs5RqIAT from awx-task-f9bf5d469-qj5zd via awx-task-f9bf5d469-qj5zd
DEBUG 2024/03/19 10:37:23 Sending routing update XDyU90R5. Connections: awx-task-f9bf5d469-qj5zd(1.00)
DEBUG 2024/03/19 10:37:32 Received routing update kEq8st8k from awx-task-f9bf5d469-qj5zd via awx-task-f9bf5d469-qj5zd
DEBUG 2024/03/19 10:37:33 Sending routing update IbhuLFA0. Connections: awx-task-f9bf5d469-qj5zd(1.00)
DEBUG 2024/03/19 10:37:38 Received service advertisement &{0xc00030cde0 false}
DEBUG 2024/03/19 10:37:42 Received routing update TyTDcp98 from awx-task-f9bf5d469-qj5zd via awx-task-f9bf5d469-qj5zd
DEBUG 2024/03/19 10:37:43 Sending routing update IaFKrqPC. Connections: awx-task-f9bf5d469-qj5zd(1.00)
DEBUG 2024/03/19 10:37:52 Received routing update Wj1RI10Y from awx-task-f9bf5d469-qj5zd via awx-task-f9bf5d469-qj5zd
DEBUG 2024/03/19 10:37:53 Sending routing update hkn64Ynx. Connections: awx-task-f9bf5d469-qj5zd(1.00)
DEBUG 2024/03/19 10:38:02 Received routing update WPRksA1Q from awx-task-f9bf5d469-qj5zd via awx-task-f9bf5d469-qj5zd
DEBUG 2024/03/19 10:38:03 Sending routing update RMtwlVE8. Connections: awx-task-f9bf5d469-qj5zd(1.00)
DEBUG 2024/03/19 10:38:12 Received routing update UJj1tIrn from awx-task-f9bf5d469-qj5zd via awx-task-f9bf5d469-qj5zd
DEBUG 2024/03/19 10:38:13 Sending routing update Q2o6fGlj. Connections: awx-task-f9bf5d469-qj5zd(1.00)
DEBUG 2024/03/19 10:38:16 Client connected to control service awx-task-f9bf5d469-qj5zd:52pg7Zd6
ERROR 2024/03/19 10:38:16 could not verify signature: token is expired by 58m56.819980616s
DEBUG 2024/03/19 10:38:16 Client disconnected from control service awx-task-f9bf5d469-qj5zd:52pg7Zd6

**Comment by 2and3makes23** [comment]
/Edit: Below issue was probably exclusively caused by our way of redeploying AWX (removing its resources from cluster), making the Operator create a new worksign key pair each time (which in turn rendered the execution node´s key obsolete). For us, the solution was precreating/ensuring a constant `awx-receptor-work-signing` secret from our deployment pipeline, which the operator leaves untouched.

Original message below:

-----------

Me too.
Running AWX 24.6.1 on an Openshift cluster, with [custom receptor-ca](https://ansible.readthedocs.io/projects/awx-operator/en/latest/user-guide/advanced-configuration/custom-receptor-certs.html) configured and resp. secrets mounted on containers (I can see every node having the same receptor ca.crt file).

Running jobs on pods within cluster and on execution node works.
Shortly after AWX is redeployed using AWX Operator (passing the same config that worked before, incl. receptor-ca), on execution node receptor logs:
`ERROR 2024/09/11 17:47:02 : could not verify signature: crypto/rsa: verification error`

And (execution node) instance health check says:
`Remote error: ERROR: could not parse response: ERROR: could not verify signature: crypto/rsa: verification error`

Running a job on execution node:
```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/tasks/jobs.py", line 605, in run
    res = receptor_job.run()
          ^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/tasks/receptor.py", line 403, in run
    res = self._run_internal(receptor_ctl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/tasks/receptor.py", line 430, in _run_internal
    result = receptor_ctl.submit_work(payload=sockout.makefile('rb'), **work_submit_kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/receptorctl/socket_interface.py", line 247, in submit_work
    raise RuntimeError(f"Remote error: {text}")
RuntimeError: Remote error: ERROR: could not parse response: ERROR: could not verify signature: crypto/rsa: verification error
```

Rerunning installer_bundle fixes the issue, via the task `Distribute public work signing key` (I think).

So if I understand this correctly, you currently either deactivate work_signing or redistribute the public work signing key on every AWX redeployment.
Or maybe I miss something/misunderstand, any guidance is much appreciated - thank you! :)
